function [a, movelist] = Stage1side(a, movelist)
% Center piece on bottom is a[8,8]
center_color = a(8,8);
right_side =  a(8,9) == center_color;
left_side = a(8,7) == center_color;
top_side = a(7,8) == center_color;
bottom_side = a(9,8) == center_color;
all = right_side && left_side && top_side && bottom_side;
if (all == 1)
    return
end
if (a(2,9) == center_color) %Begin top face
    if (a(8,9) ~= center_color)
        a = R(a);
        a = R(a);
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 1;
    elseif (a(8,7) ~= center_color)
        a = U(a);
        a = U(a);
        a = L(a);
        a = L(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 3;
    elseif (a(7,8) ~= center_color)
        a = D(a);
        a = R(a);
        a = R(a);
        a = Di(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 8;
    elseif (a(9,8) ~= center_color)
        a = Di(a);
        a = R(a);
        a = R(a);
        a = D(a);
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 7;
    end
elseif (a(2,7) == center_color)
    if (a(8,7) ~= center_color)
        a = L(a);
        a = L(a);
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = U(a);
        a = U(a);
        a = R(a);
        a = R(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 1;
    elseif (a(7,8) ~= center_color)
        a = Di(a);
        a = L(a);
        a = L(a);
        a = D(a);
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 7;
    elseif (a(9,8) ~= center_color)
        a = D(a);
        a = L(a);
        a = L(a);
        a = Di(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 8;
    end
elseif (a(1,8) == center_color)
    if (a(9,8) ~= center_color)
        a = B(a);
        a = B(a);
        movelist(length(movelist)+1) = 5;
        movelist(length(movelist)+1) = 5;
    elseif (a(8,7) ~= center_color)
        a = Ui(a);
        a = L(a);
        a = L(a);
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = U(a);
        a = R(a);
        a = R(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 1;
    elseif (a(7,8) ~= center_color)
        a = U(a);
        a = U(a);
        a = F(a);
        a = F(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 9;
    end
elseif (a(3,8) == center_color)
    if (a(7,8) ~= center_color)
        a = F(a);
        a = F(a);
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 9;
    elseif (a(9,8) ~= center_color)
        a = U(a);
        a = U(a);
        a = B(a);
        a = B(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 5;
        movelist(length(movelist)+1) = 5;
    elseif (a(8,7) ~= center_color)
        a = U(a);
        a = L(a);
        a = L(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = Ui(a);
        a = R(a);
        a = R(a);
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 1; %End top face
    end
elseif (a(5,9) == center_color) %Begin Middle Face
    if (a(8,9) ~= center_color)
        a = Ri(a);
        movelist(length(movelist)+1) = 2;
    elseif (a(7,8) ~= center_color)
        a = D(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 2;
    elseif (a(9,8) ~= center_color)
        a = Di(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 2;
    elseif (a(8,7) ~= center_color)
        a = D(a);
        a = D(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 2;
    end
elseif (a(5,7) == center_color)
    if (a(8,7) ~= center_color)
        a = L(a);
        movelist(length(movelist)+1) = 3;
    elseif (a(7,8) ~= center_color)
        a = Di(a);
        a = L(a);
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 3;
    elseif (a(9,8) ~= center_color)
        a = D(a);
        a = L(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = D(a);
        a = D(a);
        a = L(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 3;
    end
elseif (a(4,8) == center_color)
    if (a(7,8) ~= center_color)
        a = F(a);
        a = HL(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
    elseif (a(8,7) ~= center_color)
        a = D(a);
        a = Fi(a);
        a = HR(a);
        a = F(a);
        a = Di(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 10;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 8;
    elseif (a(8,9) ~= center_color)
        a = Di(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = D(a);
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
        movelist(length(movelist)+1) = 8;
    elseif (a(9,8) ~= center_color)
        a = D(a);
        a = D(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = Di(a);
        a = Di(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 8;
    end
elseif (a(6,8) == center_color)
    if (a(7,8) ~= center_color)
        a = U(a);
        a = U(a);
        a = HL(a);
        a = Di(a);
        a = VD(a);
        a = HR(a);
        a = D(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 16;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 7;
    elseif (a(9,8) ~= center_color)
        a = B(a);
        a = B(a);
        a = HL(a);
        a = U(a);
        a = VU(a);
        a = Ui(a);
        a = HR(a);
        movelist(length(movelist)+1) = 5;
        movelist(length(movelist)+1) = 5;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 15;
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 13;
    elseif (a(8,7) ~= center_color)
        a = Ui(a);
        a = L(a);
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = U(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 2; %End Middle Face
    end
elseif (a(4,5) == center_color) %Start Left Face
    if (a(7,8) ~= center_color)
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
    elseif (a(8,9) ~= center_color)
        a = Di(a);
        a = VU(a);
        a = Ui(a);
        a = VD(a);
        movelist(length(movelist)+1) = 8;
        movelist(length(movelist)+1) = 15;
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 16;
    elseif (a(8,7) ~= center_color)
        a = D(a);
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 7;
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
    elseif (a(9,8) ~= center_color)
        a = Li(a);
        a = B(a);
        movelist(length(movelist)+1) = 4;
        movelist(length(movelist)+1) = 5;
    end
elseif (a(5,6) == center_color)
    if (a(7,8) ~= center_color)
        a = Fi(a);
        movelist(length(movelist)+1) = 10;
    elseif (a(8,7) ~= center_color)
        a = HL(a);
        a = Li(a);
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 4;
    elseif (a(9,8) ~= center_color)
        a = HR(a);
        a = HR(a);
        a = Bi(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 6;
    elseif (a(8,9) ~= center_color)
        a = HR(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 2;
    end
elseif (a(6,5) == center_color)
    if (a(8,7) ~= center_color)
        a = L(a);
        a = HR(a);
        a = L(a);
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = L(a);
        a = HL(a);
        a = R(a);
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 1;
    elseif (a(7,8) ~= center_color)
        a = Li(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 4;
        movelist(length(movelist)+1) = 10;
    elseif (a(9,8) ~= center_color)
        a = L(a);
        a = B(a);
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 5;
    end
elseif (a(5,4) == center_color)
    if (a(9,8) ~= center_color)
        a = B(a);
        movelist(length(movelist)+1) = 5;
    elseif (a(8,7) ~= center_color)
        a = HR(a);
        a = L(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = HL(a);
        a = R(a);
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 1;
    elseif (a(7,8) ~= center_color)
        a = HR(a);
        a = HR(a);
        a = F(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 9; %End left face
    end
elseif (a(4,11) == center_color) %Begin right face
    if (a(8,9) ~= center_color)
        a = R(a);
        a = HL(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 2;
    elseif (a(8,7) ~= center_color)
        a = U(a);
        a = U(a);
        a = Li(a);
        a = HR(a);
        a = Li(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 4;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 4;
    elseif (a(7,8) ~= center_color)
        a = U(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
    elseif (a(9,8) ~= center_color)
        a = Ui(a);
        a = B(a);
        a = HL(a);
        a = Bi(a);
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 5;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 6;
    end
elseif (a(5,12) == center_color)
    if (a(9,8) ~= center_color)
        a = Bi(a);
        movelist(length(movelist)+1) = 6;
    elseif (a(7,8) ~= center_color)
        a = HL(a);
        a = HL(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
    elseif (a(8,9) ~= center_color)
        a = HL(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 2;
    elseif (a(8,7) ~= center_color)
        a = HR(a);
        a = Li(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 4;
    end
elseif (a(6,11) == center_color)
    a = Ri(a);
    a = HL(a);
    a = Ri(a);
    movelist(length(movelist)+1) = 2;
    movelist(length(movelist)+1) = 14;
    movelist(length(movelist)+1) = 2;
elseif (a(5,10) == center_color)
    if (a(7,8) ~= center_color)
        a = F(a);
        movelist(length(movelist)+1) = 9;
    elseif (a(8,9) ~= center_color)
        a = HR(a);
        a = R(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 1;
    elseif (a(8,7) ~= center_color)
        a = HL(a);
        a = L(a);
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 3;
    elseif (a(9,8) ~= center_color)
        a = HL(a);
        a = HL(a);
        a = B(a); %End Right Face
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 5;
    end
elseif (a(4,2) == center_color) %Start Back face
    if (a(9,8) ~= center_color)
        a = B(a);
        a = HL(a);
        a = Bi(a);
        movelist(length(movelist)+1) = 5;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 6;
    elseif (a(7,8) ~= center_color)
        a = U(a);
        a = U(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 9;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 10;
    elseif (a(8,7) ~= center_color)
        a = Ui(a);
        a = Li(a);
        a = HR(a);
        a = L(a);
        movelist(length(movelist)+1) = 12;
        movelist(length(movelist)+1) = 4;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 3;
    elseif (a(8,9) ~= center_color)
        a = U(a);
        a = R(a);
        a = HL(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 11;
        movelist(length(movelist)+1) = 1;
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 2;
    end
elseif (a(6,2) == center_color)
    a = B(a);
    a = HR(a);
    a = B(a);
    movelist(length(movelist)+1) = 5;
    movelist(length(movelist)+1) = 13;
    movelist(length(movelist)+1) = 5;
elseif (a(5,1) == center_color)
    if (a(7,8) ~= center_color)
        a = HL(a);
        a = F(a);
        movelist(length(movelist)+1) = 14;
        movelist(length(movelist)+1) = 9;
    elseif (a(9,8) ~= center_color)
        a = HR(a);
        a = B(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 5;
    elseif (a(8,9) ~= center_color)
        a = R(a);
        movelist(length(movelist)+1) = 1;
    elseif (a(8,7) ~= center_color)
        a = HR(a);
        a = HR(a);
        a = L(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 3;
    end
elseif (a(5,3) == center_color)
    if (a(8,7) ~= center_color)
        a = Li(a);
        movelist(length(movelist)+1) = 4;
    elseif (a(8,9) ~= center_color)
        a = HR(a);
        a = HR(a);
        a = Ri(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 2;
    elseif (a(7,8) ~= center_color)
        a = HR(a);
        a = Fi(a);
        movelist(length(movelist)+1) = 13;
        movelist(length(movelist)+1) = 10;
    elseif (a(9,8) ~= center_color)
        a = L(a);
        a = Bi(a);
        movelist(length(movelist)+1) = 3;
        movelist(length(movelist)+1) = 6;%End Back side
    end
end
end
