function [a, movelist] = Stage1color(a, movelist)

center_color = a(8, 8);
if (center_color == 'w')
    while (a(6,8) ~= 'g')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,11) ~= 'o')
        if (a(6,5) == 'o')
            a = D(a);
            a = VU(a);
            a = U(a);
            a = VD(a);
            a = Ui(a);
            a = D(a);
            a = D(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = HL(a);
            a = Li(a);
            a = Bi(a);
            a = L(a);
            a = U(a);
            a = B(a);
            a = U(a);
            a = Bi(a);
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 6;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 5;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 6;
        elseif (a(6,2) == 'o')
            a = VD(a);
            a = U(a);
            a = VU(a);
            a = Di(a);
            a = U(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = Ri(a);
            a = HL(a);
            a = R(a);
            a = Di(a);
            a = F(a);
            a = HR(a);
            a = HR(a);
            a = Fi(a);
            a = HL(a);
            a = L(a);
            a = F(a);
            a = Li(a);
            a = Ui(a);
            a = Fi(a);
            a = Ui(a);
            a = F(a);
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 2;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 1;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 9;
        end
    end
    while (a(6,8) ~= 'g')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,5) ~= 'r')
        a = VD(a);
        a = Ui(a);
        a = VU(a);
        a = D(a);
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = Fi(a);
        a = Li(a);
        a = F(a);
        a = U(a);
        a = L(a);
        a = U(a);
        a = Li(a);
    end

elseif (center_color == 'g')
    while (a(6,8) ~= 'y')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,11) ~= 'o')
        if (a(6,5) == 'o')
            a = D(a);
            a = VU(a);
            a = U(a);
            a = VD(a);
            a = Ui(a);
            a = D(a);
            a = D(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = HL(a);
            a = Li(a);
            a = Bi(a);
            a = L(a);
            a = U(a);
            a = B(a);
            a = U(a);
            a = Bi(a);
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 6;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 5;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 6;
        elseif (a(6,2) == 'o')
            a = VD(a);
            a = U(a);
            a = VU(a);
            a = Di(a);
            a = U(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = Ri(a);
            a = HL(a);
            a = R(a);
            a = Di(a);
            a = F(a);
            a = HR(a);
            a = HR(a);
            a = Fi(a);
            a = HL(a);
            a = L(a);
            a = F(a);
            a = Li(a);
            a = Ui(a);
            a = Fi(a);
            a = Ui(a);
            a = F(a);
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 2;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 1;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 9;
        end
    end
    while (a(6,8) ~= 'y')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,5) ~= 'r')
        a = VD(a);
        a = Ui(a);
        a = VU(a);
        a = D(a);
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = Fi(a);
        a = Li(a);
        a = F(a);
        a = U(a);
        a = L(a);
        a = U(a);
        a = Li(a);
    end


elseif (center_color == 'y')
    while (a(6,8) ~= 'b')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,11) ~= 'o')
        if (a(6,5) == 'o')
            a = D(a);
            a = VU(a);
            a = U(a);
            a = VD(a);
            a = Ui(a);
            a = D(a);
            a = D(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = HL(a);
            a = Li(a);
            a = Bi(a);
            a = L(a);
            a = U(a);
            a = B(a);
            a = U(a);
            a = Bi(a);
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 6;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 5;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 6;
        elseif (a(6,2) == 'o')
            a = VD(a);
            a = U(a);
            a = VU(a);
            a = Di(a);
            a = U(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = Ri(a);
            a = HL(a);
            a = R(a);
            a = Di(a);
            a = F(a);
            a = HR(a);
            a = HR(a);
            a = Fi(a);
            a = HL(a);
            a = L(a);
            a = F(a);
            a = Li(a);
            a = Ui(a);
            a = Fi(a);
            a = Ui(a);
            a = F(a);
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 2;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 1;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 9;
        end
    end
    while (a(6,8) ~= 'b')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,5) ~= 'r')
        a = VD(a);
        a = Ui(a);
        a = VU(a);
        a = D(a);
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = Fi(a);
        a = Li(a);
        a = F(a);
        a = U(a);
        a = L(a);
        a = U(a);
        a = Li(a);
    end
elseif (center_color == 'b')
    while (a(6,8) ~= 'w')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(5,10) ~= 'o')
        if (a(5,4) == 'o')
            a = D(a);
            a = VU(a);
            a = U(a);
            a = VD(a);
            a = Ui(a);
            a = D(a);
            a = D(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = HL(a);
            a = Li(a);
            a = Bi(a);
            a = L(a);
            a = U(a);
            a = B(a);
            a = U(a);
            a = Bi(a);
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 6;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 5;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 6;
        elseif (a(6,2) == 'o')
            a = VD(a);
            a = U(a);
            a = VU(a);
            a = Di(a);
            a = U(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = Ri(a);
            a = HL(a);
            a = R(a);
            a = Di(a);
            a = F(a);
            a = HR(a);
            a = HR(a);
            a = Fi(a);
            a = HL(a);
            a = L(a);
            a = F(a);
            a = Li(a);
            a = Ui(a);
            a = Fi(a);
            a = Ui(a);
            a = F(a);
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 2;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 1;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 9;
        end
    end
    while (a(6,8) ~= 'w')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,5) ~= 'r')
        a = VD(a);
        a = Ui(a);
        a = VU(a);
        a = D(a);
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = Fi(a);
        a = Li(a);
        a = F(a);
        a = U(a);
        a = L(a);
        a = U(a);
        a = Li(a);
    end
elseif (center_color == 'o')
    while (a(6,8) ~= 'w')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,11) ~= 'g')
        if (a(6,5) == 'g')
            a = D(a);
            a = VU(a);
            a = U(a);
            a = VD(a);
            a = Ui(a);
            a = D(a);
            a = D(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = HL(a);
            a = Li(a);
            a = Bi(a);
            a = L(a);
            a = U(a);
            a = B(a);
            a = U(a);
            a = Bi(a);
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 6;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 5;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 6;
        elseif (a(6,2) == 'g')
            a = VD(a);
            a = U(a);
            a = VU(a);
            a = Di(a);
            a = U(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = Ri(a);
            a = HL(a);
            a = R(a);
            a = Di(a);
            a = F(a);
            a = HR(a);
            a = HR(a);
            a = Fi(a);
            a = HL(a);
            a = L(a);
            a = F(a);
            a = Li(a);
            a = Ui(a);
            a = Fi(a);
            a = Ui(a);
            a = F(a);
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 2;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 1;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 9;
        end
    end
    while (a(6,8) ~= 'w')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,5) ~= 'b')
        a = VD(a);
        a = Ui(a);
        a = VU(a);
        a = D(a);
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = Fi(a);
        a = Li(a);
        a = F(a);
        a = U(a);
        a = L(a);
        a = U(a);
        a = Li(a);
    end

elseif (center_color == 'r')
    while (a(6,8) ~= 'b')
        a = D(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,11) ~= 'y')
        if (a(6,5) == 'y')
            a = D(a);
            a = VU(a);
            a = U(a);
            a = VD(a);
            a = Ui(a);
            a = D(a);
            a = D(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = HL(a);
            a = Li(a);
            a = Bi(a);
            a = L(a);
            a = U(a);
            a = B(a);
            a = U(a);
            a = Bi(a);
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 7;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 6;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 5;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 6;
        elseif (a(6,2) == 'y')
            a = VD(a);
            a = U(a);
            a = VU(a);
            a = Di(a);
            a = U(a);
            a = F(a);
            a = HL(a);
            a = Fi(a);
            a = Ri(a);
            a = HL(a);
            a = R(a);
            a = Di(a);
            a = F(a);
            a = HR(a);
            a = HR(a);
            a = Fi(a);
            a = HL(a);
            a = L(a);
            a = F(a);
            a = Li(a);
            a = Ui(a);
            a = Fi(a);
            a = Ui(a);
            a = F(a);
            movelist(length(movelist)+1) = 16;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 15;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 11;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 2;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 1;
            movelist(length(movelist)+1) = 8;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 13;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 14;
            movelist(length(movelist)+1) = 3;
            movelist(length(movelist)+1) = 9;
            movelist(length(movelist)+1) = 4;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 10;
            movelist(length(movelist)+1) = 12;
            movelist(length(movelist)+1) = 9;
        end
    end
    while (a(6,8) ~= 'b')
        a = Di(a);
        movelist(length(movelist)+1) = 7;
    end
    if (a(6,5) ~= 'w')
        a = VD(a);
        a = Ui(a);
        a = VU(a);
        a = D(a);
        a = Ui(a);
        a = F(a);
        a = HL(a);
        a = Fi(a);
        a = Fi(a);
        a = Li(a);
        a = F(a);
        a = U(a);
        a = L(a);
        a = U(a);
        a = Li(a);
    end
end

